// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameProjectTaskVisibilityUser = "pre_project_task_visibility_users"

// ProjectTaskVisibilityUser mapped from table <pre_project_task_visibility_users>
type ProjectTaskVisibilityUser struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ProjectID int64     `gorm:"column:project_id;comment:项目ID" json:"project_id"` // 项目ID
	TaskID    int64     `gorm:"column:task_id;comment:任务ID" json:"task_id"`       // 任务ID
	Userid    int64     `gorm:"column:userid;comment:成员ID" json:"userid"`         // 成员ID
	CreatedAt time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName ProjectTaskVisibilityUser's table name
func (*ProjectTaskVisibilityUser) TableName() string {
	return TableNameProjectTaskVisibilityUser
}
