// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameProject = "pre_projects"

// Project mapped from table <pre_projects>
type Project struct {
	ID             int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name           string         `gorm:"column:name;comment:名称" json:"name"`                         // 名称
	Desc           string         `gorm:"column:desc;comment:描述、备注" json:"desc"`                      // 描述、备注
	Userid         int64          `gorm:"column:userid;comment:创建人" json:"userid"`                    // 创建人
	Personal       bool           `gorm:"column:personal;comment:是否个人项目" json:"personal"`             // 是否个人项目
	UserSimple     string         `gorm:"column:user_simple;comment:成员总数|1,2,3" json:"user_simple"`   // 成员总数|1,2,3
	DialogID       int64          `gorm:"column:dialog_id;comment:聊天会话ID" json:"dialog_id"`           // 聊天会话ID
	ArchivedAt     time.Time      `gorm:"column:archived_at;comment:归档时间" json:"archived_at"`         // 归档时间
	ArchivedUserid int64          `gorm:"column:archived_userid;comment:归档会员" json:"archived_userid"` // 归档会员
	CreatedAt      time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt      time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt      gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName Project's table name
func (*Project) TableName() string {
	return TableNameProject
}
