// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameProjectFlowItem = "pre_project_flow_items"

// ProjectFlowItem mapped from table <pre_project_flow_items>
type ProjectFlowItem struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ProjectID int64     `gorm:"column:project_id;comment:项目ID" json:"project_id"` // 项目ID
	FlowID    int64     `gorm:"column:flow_id;comment:流程ID" json:"flow_id"`       // 流程ID
	Name      string    `gorm:"column:name;comment:名称" json:"name"`               // 名称
	Status    string    `gorm:"column:status;comment:状态" json:"status"`           // 状态
	Turns     string    `gorm:"column:turns;comment:可流转" json:"turns"`            // 可流转
	Userids   string    `gorm:"column:userids;comment:状态负责人ID" json:"userids"`    // 状态负责人ID
	Usertype  string    `gorm:"column:usertype;comment:流转模式" json:"usertype"`     // 流转模式
	Userlimit int32     `gorm:"column:userlimit;comment:限制负责人" json:"userlimit"`  // 限制负责人
	Columnid  int64     `gorm:"column:columnid;comment:对应的项目列表" json:"columnid"`  // 对应的项目列表
	Sort      int32     `gorm:"column:sort;comment:排序" json:"sort"`               // 排序
	CreatedAt time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName ProjectFlowItem's table name
func (*ProjectFlowItem) TableName() string {
	return TableNameProjectFlowItem
}
