// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameProjectTaskUser = "pre_project_task_users"

// ProjectTaskUser mapped from table <pre_project_task_users>
type ProjectTaskUser struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ProjectID int64     `gorm:"column:project_id;comment:项目ID" json:"project_id"`             // 项目ID
	TaskID    int64     `gorm:"column:task_id;comment:任务ID" json:"task_id"`                   // 任务ID
	TaskPid   int64     `gorm:"column:task_pid;comment:任务ID（如果是子任务则是父级任务ID）" json:"task_pid"` // 任务ID（如果是子任务则是父级任务ID）
	Userid    int64     `gorm:"column:userid;comment:成员ID" json:"userid"`                     // 成员ID
	Owner     int32     `gorm:"column:owner;comment:是否任务负责人" json:"owner"`                    // 是否任务负责人
	CreatedAt time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName ProjectTaskUser's table name
func (*ProjectTaskUser) TableName() string {
	return TableNameProjectTaskUser
}
