// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameProjectFlow = "pre_project_flows"

// ProjectFlow mapped from table <pre_project_flows>
type ProjectFlow struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ProjectID int64     `gorm:"column:project_id;comment:项目ID" json:"project_id"` // 项目ID
	Name      string    `gorm:"column:name;comment:流程名称" json:"name"`             // 流程名称
	CreatedAt time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName ProjectFlow's table name
func (*ProjectFlow) TableName() string {
	return TableNameProjectFlow
}
