// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameProjectTask = "pre_project_tasks"

// ProjectTask mapped from table <pre_project_tasks>
type ProjectTask struct {
	ID             int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ParentID       int64          `gorm:"column:parent_id;comment:父级任务ID" json:"parent_id"`                                 // 父级任务ID
	ProjectID      int64          `gorm:"column:project_id;comment:项目ID" json:"project_id"`                                 // 项目ID
	ColumnID       int64          `gorm:"column:column_id;comment:列表ID" json:"column_id"`                                   // 列表ID
	DialogID       int64          `gorm:"column:dialog_id;comment:聊天会话ID" json:"dialog_id"`                                 // 聊天会话ID
	FlowItemID     int64          `gorm:"column:flow_item_id;comment:工作流状态ID" json:"flow_item_id"`                          // 工作流状态ID
	FlowItemName   string         `gorm:"column:flow_item_name;comment:工作流状态名称" json:"flow_item_name"`                      // 工作流状态名称
	Name           string         `gorm:"column:name;comment:标题" json:"name"`                                               // 标题
	Color          string         `gorm:"column:color;comment:颜色" json:"color"`                                             // 颜色
	Desc           string         `gorm:"column:desc;comment:描述" json:"desc"`                                               // 描述
	StartAt        time.Time      `gorm:"column:start_at;comment:计划开始时间" json:"start_at"`                                   // 计划开始时间
	EndAt          time.Time      `gorm:"column:end_at;comment:计划结束时间" json:"end_at"`                                       // 计划结束时间
	ArchivedAt     time.Time      `gorm:"column:archived_at;comment:归档时间" json:"archived_at"`                               // 归档时间
	ArchivedUserid int64          `gorm:"column:archived_userid;comment:归档会员" json:"archived_userid"`                       // 归档会员
	ArchivedFollow int32          `gorm:"column:archived_follow;comment:跟随项目归档（项目取消归档时任务也取消归档）" json:"archived_follow"`     // 跟随项目归档（项目取消归档时任务也取消归档）
	CompleteAt     time.Time      `gorm:"column:complete_at;comment:完成时间" json:"complete_at"`                               // 完成时间
	Userid         int64          `gorm:"column:userid;comment:创建人" json:"userid"`                                          // 创建人
	Visibility     int32          `gorm:"column:visibility;default:1;comment:任务可见性：1-项目人员 2-任务人员 3-指定成员" json:"visibility"` // 任务可见性：1-项目人员 2-任务人员 3-指定成员
	PLevel         int32          `gorm:"column:p_level;comment:优先级" json:"p_level"`                                        // 优先级
	PName          string         `gorm:"column:p_name;comment:优先级名称" json:"p_name"`                                        // 优先级名称
	PColor         string         `gorm:"column:p_color;comment:优先级颜色" json:"p_color"`                                      // 优先级颜色
	Sort           int32          `gorm:"column:sort;comment:排序(ASC)" json:"sort"`                                          // 排序(ASC)
	Loop           string         `gorm:"column:loop;comment:重复周期" json:"loop"`                                             // 重复周期
	LoopAt         time.Time      `gorm:"column:loop_at;comment:下一次重复时间" json:"loop_at"`                                    // 下一次重复时间
	CreatedAt      time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt      time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt      gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	DeletedUserid  int64          `gorm:"column:deleted_userid;comment:删除会员" json:"deleted_userid"` // 删除会员
}

// TableName ProjectTask's table name
func (*ProjectTask) TableName() string {
	return TableNameProjectTask
}
