// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameProjectTaskFile = "pre_project_task_files"

type ProjectTaskFile struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ProjectID int64     `gorm:"column:project_id;comment:项目ID" json:"project_id"` // 项目ID
	TaskID    int64     `gorm:"column:task_id;comment:任务ID" json:"task_id"`       // 任务ID
	Name      string    `gorm:"column:name;comment:文件名称" json:"name"`             // 文件名称
	Size      int64     `gorm:"column:size;comment:文件大小(B)" json:"size"`          // 文件大小(B)
	Ext       string    `gorm:"column:ext;comment:文件格式" json:"ext"`               // 文件格式
	Path      string    `gorm:"column:path;comment:文件地址" json:"path"`             // 文件地址
	Thumb     string    `gorm:"column:thumb;comment:缩略图" json:"thumb"`            // 缩略图
	Userid    int64     `gorm:"column:userid;comment:上传用户ID" json:"userid"`       // 上传用户ID
	Download  int32     `gorm:"column:download;comment:下载次数" json:"download"`     // 下载次数
	CreatedAt time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at" json:"updated_at"`
}

func (*ProjectTaskFile) TableName() string {
	return TableNameProjectTaskFile
}
