// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameProjectTaskContent = "pre_project_task_contents"

// ProjectTaskContent mapped from table <pre_project_task_contents>
type ProjectTaskContent struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ProjectID int64     `gorm:"column:project_id;comment:项目ID" json:"project_id"` // 项目ID
	TaskID    int64     `gorm:"column:task_id;comment:任务ID" json:"task_id"`       // 任务ID
	Userid    int64     `gorm:"column:userid;comment:用户ID" json:"userid"`         // 用户ID
	Desc      string    `gorm:"column:desc;comment:内容描述" json:"desc"`             // 内容描述
	Content   string    `gorm:"column:content;comment:内容" json:"content"`         // 内容
	CreatedAt time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName ProjectTaskContent's table name
func (*ProjectTaskContent) TableName() string {
	return TableNameProjectTaskContent
}
